services:
  db:
    image: postgres:14-alpine
    container_name: auth_db
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=auth_db
    volumes:
      - auth_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d auth_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog
    ports:
      - "8025:8025" 
    networks:
      - default

  auth-service:
    build: .  
    container_name: auth_service
    command: >
      sh -c "sleep 5 && 
             python manage.py migrate --no-input && 
             python manage.py runserver 0.0.0.0:5050"
    volumes:
     - .:/app 

    ports:
      - "5050:5050"
    environment:
      - DB_HOST=db
      - DB_NAME=auth_db
      - DB_USER=myuser
      - DB_PASSWORD=mypassword

      - EMAIL_HOST=mailhog
      - EMAIL_PORT=1025
      - EMAIL_USE_TLS=False
      - EMAIL_USE_SSL=False
      - EMAIL_USER=
      - EMAIL_PASSWORD=
      - DEFAULT_FROM_EMAIL=email@example.com

      - SECRET_KEY=your_super_secret_django_key_here

    depends_on:
      db:
        condition: service_healthy
      mailhog:
        condition: service_started

volumes:
  auth_db_data: