version: '3.8'

services:
  db:
    image: postgres:14-alpine
    container_name: auth_db
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=auth_db
    volumes:
      - auth_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d auth_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  auth-service:
    build: .  
    container_name: auth_service
    command: python manage.py runserver 0.0.0.0:5050
    #volumes:
    #  - .:/app  # This maps your local code into the container for live-reloading

    ports:
      - "5050:5050"
    environment:
      - DB_HOST=db
      - DB_NAME=auth_db
      - DB_USER=myuser
      - DB_PASSWORD=mypassword

      - EMAIL_HOST=smtp-relay.brevo.com
      - EMAIL_PORT=587 
      - EMAIL_USER=9c4025001@smtp-brevo.com
      - EMAIL_PASSWORD=pxRmvH7IyJZ6QTOj
      - DEFAULT_FROM_EMAIL=email@example.com # We would need an actual domain to send email through SMTP
      
      - SECRET_KEY=your_super_secret_django_key_here

    depends_on:
      db:
        condition: service_healthy

volumes:
  auth_db_data: